# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(914, 670)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 296, 173))
        self.calendarWidget.setObjectName("calendarWidget")
        self.realDisk_listView = QtWidgets.QListView(Form)
        self.realDisk_listView.setGeometry(QtCore.QRect(10, 240, 191, 381))
        self.realDisk_listView.setObjectName("realDisk_listView")
        self.realDisk_label = QtWidgets.QLabel(Form)
        self.realDisk_label.setGeometry(QtCore.QRect(10, 210, 60, 16))
        self.realDisk_label.setObjectName("realDisk_label")
        self.simDisk_label = QtWidgets.QLabel(Form)
        self.simDisk_label.setGeometry(QtCore.QRect(230, 210, 60, 16))
        self.simDisk_label.setObjectName("simDisk_label")
        self.refresh_btn = QtWidgets.QPushButton(Form)
        self.refresh_btn.setGeometry(QtCore.QRect(300, 10, 113, 32))
        self.refresh_btn.setObjectName("refresh_btn")
        self.saveSimDisk_btn = QtWidgets.QPushButton(Form)
        self.saveSimDisk_btn.setGeometry(QtCore.QRect(300, 50, 113, 32))
        self.saveSimDisk_btn.setObjectName("saveSimDisk_btn")
        self.oprateList_label = QtWidgets.QLabel(Form)
        self.oprateList_label.setGeometry(QtCore.QRect(460, 210, 81, 16))
        self.oprateList_label.setObjectName("oprateList_label")
        self.mkdir_btn = QtWidgets.QPushButton(Form)
        self.mkdir_btn.setGeometry(QtCore.QRect(300, 90, 113, 32))
        self.mkdir_btn.setObjectName("mkdir_btn")
        self.touch_btn = QtWidgets.QPushButton(Form)
        self.touch_btn.setGeometry(QtCore.QRect(300, 130, 113, 32))
        self.touch_btn.setObjectName("touch_btn")
        self.rm_btn = QtWidgets.QPushButton(Form)
        self.rm_btn.setGeometry(QtCore.QRect(430, 90, 113, 32))
        self.rm_btn.setObjectName("rm_btn")
        self.move_btn = QtWidgets.QPushButton(Form)
        self.move_btn.setGeometry(QtCore.QRect(430, 130, 113, 32))
        self.move_btn.setObjectName("move_btn")
        self.depart_btn = QtWidgets.QPushButton(Form)
        self.depart_btn.setGeometry(QtCore.QRect(780, 80, 113, 32))
        self.depart_btn.setObjectName("depart_btn")
        self.FF_radioBtn = QtWidgets.QRadioButton(Form)
        self.FF_radioBtn.setGeometry(QtCore.QRect(590, 10, 100, 20))
        self.FF_radioBtn.setObjectName("FF_radioBtn")
        self.BF_radioBtn = QtWidgets.QRadioButton(Form)
        self.BF_radioBtn.setGeometry(QtCore.QRect(710, 10, 100, 20))
        self.BF_radioBtn.setObjectName("BF_radioBtn")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(420, 30, 141, 21))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.drawBack_btn = QtWidgets.QPushButton(Form)
        self.drawBack_btn.setGeometry(QtCore.QRect(780, 190, 113, 32))
        self.drawBack_btn.setObjectName("drawBack_btn")
        self.simDisk_treeView = QtWidgets.QTreeView(Form)
        self.simDisk_treeView.setGeometry(QtCore.QRect(220, 240, 201, 381))
        self.simDisk_treeView.setObjectName("simDisk_treeView")
        self.workName_label = QtWidgets.QLabel(Form)
        self.workName_label.setGeometry(QtCore.QRect(590, 50, 60, 16))
        self.workName_label.setObjectName("workName_label")
        self.workSize_label = QtWidgets.QLabel(Form)
        self.workSize_label.setGeometry(QtCore.QRect(590, 80, 61, 20))
        self.workSize_label.setObjectName("workSize_label")
        self.workName_box = QtWidgets.QTextEdit(Form)
        self.workName_box.setGeometry(QtCore.QRect(650, 50, 104, 21))
        self.workName_box.setObjectName("workName_box")
        self.workSize_box = QtWidgets.QTextEdit(Form)
        self.workSize_box.setGeometry(QtCore.QRect(650, 80, 104, 21))
        self.workSize_box.setObjectName("workSize_box")
        self.workDrawbackName_box = QtWidgets.QTextEdit(Form)
        self.workDrawbackName_box.setGeometry(QtCore.QRect(650, 160, 104, 21))
        self.workDrawbackName_box.setObjectName("workDrawbackName_box")
        self.workName_label_2 = QtWidgets.QLabel(Form)
        self.workName_label_2.setGeometry(QtCore.QRect(590, 160, 60, 16))
        self.workName_label_2.setObjectName("workName_label_2")
        self.all_textBrowser = QtWidgets.QTextBrowser(Form)
        self.all_textBrowser.setGeometry(QtCore.QRect(460, 240, 401, 381))
        self.all_textBrowser.setObjectName("all_textBrowser")
        self.warn_textBrowser = QtWidgets.QTextBrowser(Form)
        self.warn_textBrowser.setGeometry(QtCore.QRect(650, 120, 101, 21))
        self.warn_textBrowser.setObjectName("warn_textBrowser")
        self.warn_label = QtWidgets.QLabel(Form)
        self.warn_label.setGeometry(QtCore.QRect(590, 120, 61, 20))
        self.warn_label.setObjectName("warn_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.realDisk_label.setText(_translate("Form", "真实磁盘"))
        self.simDisk_label.setText(_translate("Form", "模拟磁盘"))
        self.refresh_btn.setText(_translate("Form", "刷新信息"))
        self.saveSimDisk_btn.setText(_translate("Form", "储存到模拟磁盘"))
        self.oprateList_label.setText(_translate("Form", "内存分配状态"))
        self.mkdir_btn.setText(_translate("Form", "新建目录"))
        self.touch_btn.setText(_translate("Form", "新建文件"))
        self.rm_btn.setText(_translate("Form", "删除文件"))
        self.move_btn.setText(_translate("Form", "移出文件"))
        self.depart_btn.setText(_translate("Form", "分配"))
        self.FF_radioBtn.setText(_translate("Form", "首次适应"))
        self.BF_radioBtn.setText(_translate("Form", "最佳适应"))
        self.drawBack_btn.setText(_translate("Form", "回收分配内存"))
        self.workName_label.setText(_translate("Form", "作业名称"))
        self.workSize_label.setText(_translate("Form", "作业大小"))
        self.workName_label_2.setText(_translate("Form", "作业名称"))
        self.warn_label.setText(_translate("Form", "提示信息"))

